### ISSUE TITLE
harden-below-nxdomain should be set no

### ISSUE THREAD

**Issue by jcjones** [jsha/unboundtest#12]
The parameter `harden-below-nxdomain` should be set to `no` instead of the [default](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-harden-below-nxdomain) of `yes`.

Also `qname_minimisation` should be set  `no`, instead of the default `yes` as well.

**Comment by jsha** [comment]
This is deployed. Thanks!
